package com.gt.entities;
// Generated Sep 6, 2017 12:42:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Dealer generated by hbm2java
 */
public class Dealer implements java.io.Serializable {

	private int dealerCode;
	private String dealerNm;
	private Date registrationDt;
	private int dealerAddressId;
	private int contactNo;
	private String emailAddress;

	public Dealer() {
	}

	public Dealer(int dealerCode, String dealerNm, Date registrationDt, int dealerAddressId, int contactNo,
			String emailAddress) {
		this.dealerCode = dealerCode;
		this.dealerNm = dealerNm;
		this.registrationDt = registrationDt;
		this.dealerAddressId = dealerAddressId;
		this.contactNo = contactNo;
		this.emailAddress = emailAddress;
	}

	public int getDealerCode() {
		return this.dealerCode;
	}

	public void setDealerCode(int dealerCode) {
		this.dealerCode = dealerCode;
	}

	public String getDealerNm() {
		return this.dealerNm;
	}

	public void setDealerNm(String dealerNm) {
		this.dealerNm = dealerNm;
	}

	public Date getRegistrationDt() {
		return this.registrationDt;
	}

	public void setRegistrationDt(Date registrationDt) {
		this.registrationDt = registrationDt;
	}

	public int getDealerAddressId() {
		return this.dealerAddressId;
	}

	public void setDealerAddressId(int dealerAddressId) {
		this.dealerAddressId = dealerAddressId;
	}

	public int getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(int contactNo) {
		this.contactNo = contactNo;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
