package com.gt.entities;
// Generated Sep 6, 2017 12:42:20 PM by Hibernate Tools 4.3.5.Final

/**
 * Mechanic generated by hbm2java
 */
public class Mechanic implements java.io.Serializable {

	private int mechanicNo;
	private String firstNm;
	private String lastNm;
	private String specialization;
	private int experience;
	private int contactNo;
	private String emailAddress;

	public Mechanic() {
	}

	public Mechanic(int mechanicNo, String firstNm, String lastNm, String specialization, int experience, int contactNo,
			String emailAddress) {
		this.mechanicNo = mechanicNo;
		this.firstNm = firstNm;
		this.lastNm = lastNm;
		this.specialization = specialization;
		this.experience = experience;
		this.contactNo = contactNo;
		this.emailAddress = emailAddress;
	}

	public int getMechanicNo() {
		return this.mechanicNo;
	}

	public void setMechanicNo(int mechanicNo) {
		this.mechanicNo = mechanicNo;
	}

	public String getFirstNm() {
		return this.firstNm;
	}

	public void setFirstNm(String firstNm) {
		this.firstNm = firstNm;
	}

	public String getLastNm() {
		return this.lastNm;
	}

	public void setLastNm(String lastNm) {
		this.lastNm = lastNm;
	}

	public String getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}

	public int getExperience() {
		return this.experience;
	}

	public void setExperience(int experience) {
		this.experience = experience;
	}

	public int getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(int contactNo) {
		this.contactNo = contactNo;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
